---
- name: install prometheus
  hosts: prometheus
  become: true

  tasks:
    - name: create prometheus group
      group:
        name: prometheus
        system: yes

    - name: create prometheus user
      user:
        name: prometheus
        group: prometheus
        system: yes
        shell: /sbin/nologin

    - name: create prometheus data directory
      file:
        path: "{{ item }}"
        state: directory
        owner: prometheus
        group: prometheus
      loop:
        - /etc/prometheus
        - /var/lib/prometheus

    - name: download prometheus
      get_url: 
        url: https://github.com/prometheus/prometheus/releases/download/v2.47.0/prometheus-2.47.0.linux-amd64.tar.gz
        dest: /tmp

    - name: unarchive prometheus
      unarchive:
        src: /tmp/prometheus-2.47.0.linux-amd64.tar.gz
        dest: /tmp
        remote_src: true

    - name: moving binaries in /usr/local/bin
      copy:
        src: "/tmp/prometheus-2.47.0.linux-amd64/{{ item }}"
        dest: /usr/local/bin
        owner: prometheus
        group: prometheus
        mode: u=rwx,g=rwx,o=r
        remote_src: true
      loop:
        - prometheus
        - promtool

    - name: moving other files in /etc/prometheus
      copy:
        src: "/tmp/prometheus-2.47.0.linux-amd64/{{ item }}"
        dest: /etc/prometheus
        owner: prometheus
        group: prometheus
        remote_src: true
      loop:
        - console_libraries
        - consoles

    - name: moving other files in /etc/prometheus
      copy:
        src: prometheus.yml
        dest: /etc/prometheus/prometheus.yml
        owner: prometheus
        group: prometheus

    - name: copy prometheus service
      copy:
        src: prometheus.service
        dest: /etc/systemd/system
        owner: root
        group: root

    - name: reload deamon service
      systemd:
          daemon_reload: yes

    - name: Start and enable Prometheus service
      service:
        name: prometheus.service
        state: stopped
        enabled: no