- name: kill and restart the process
  hosts: all_hosts
  become: True

  tasks:
  - name: kill a process
    ignore_errors: yes
    shell: "pgrep nginx | xargs kill"

  - name: restart nginx service
    service:
      name: nginx
      state: started
