- name: using handler to skip unchange tasks
  hosts: all_hosts

  tasks:
  - name: enable a service in firewalld
    firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
    notify:
      - Reload firewalld

    handlers:
    - name: Reload firewalld
      service:
        name: firewalld
        state: reloaded
