---
- hosts: all
  become: true
  vars:
    the_user: "devops"

  tasks:
    - name: create user
      user:
        name: "{{ the_user }}"
        groups: root
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Create a SSH key
      user:
        name: "{{ the_user }}"
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa

    - name: set password
      user:
        name: "{{ the_user }}"
        password: '$6$wona9cxVsOQ4ikdk$07PwnJ1PcCLgZVBJOq4D8mn9IMe0mWvaVFqqF/c5ObEVG2NN/01rqDoUdObGXfPg29xzonJrE5xD/uGlPIDp7.'
        password_expire_min: 10
        password_expire_max: 20
