# Install Nginx using Ansbile
# Start and Enable Nginx (make it automatically up after system reboot)
# Check the status of Nginx

- name: Setup Nginx server on my severs list
  hosts: myservers
  become: True

  tasks:
  - name: Install the latest verison of nginx server
    command: amazon-linux-extras install nginx1.12=latest -y
    args:
      creates: /sbin/nginx

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: enable nginx
    service:
      name: nginx
      enabled: yes

  - name: ensure nginx is at the latest version
    command: nginx -v

  - name: get status of nginx insalled
    command: systemctl status nginx

  - name: copy file from master to hosts
    copy:
      src: /home/personal/sample.txt
      dest: /home/aman
